services:
  #service 1
  postgres:
    container_name: postgres_container
    image: postgres:15
    environment:
      POSTGRES_USER: saurabh
      POSTGRES_PASSWORD: root
      TZ: Asia/Kolkata
      PGDATA: /data/postgres
    volumes:
      - postgresvol:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - my-network
    restart: unless-stopped

  #service2
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-sau@pagadmin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadminvol:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - my-network
    restart: unless-stopped

  #service3
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
    ports:
      - "5672:5672"     #RabbitMQ Message Broker
      - "15672:15672"     #RabbitMQ Management UI
    networks:
      - my-network
    restart: unless-stopped

#Networks definition
networks:
  my-network:
    driver: bridge

#Volumes definition
volumes:
  postgresvol:
  pgadminvol:

#--------------------------MySQL Docker Config
#services:
#  mysql:
#    container_name: mysql_container
#    image: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: productdb
#      MYSQL_USER: saurabh
#      MYSQL_PASSWORD: root
#    volumes:
#      - mysql_data:/var/lib/mysql
#    ports:
#      - "3307:3306"
#    networks:
#      - mysql-network
#    restart: unless-stopped
#
#  phpmyadmin:
#    container_name: phpmyadmin_container
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - "8484:80"
#    networks:
#      - mysql-network
#    restart: unless-stopped
#
#networks:
#  mysql-network:
#    driver: bridge
#
#volumes:
#  mysql_data:
