spring:
  application:
    name: notification
  #local RabbitMQ in docker
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange:
   name: order.exchange
  queue:
   name: order.queue
  routing:
   key: order.tracking

server:
  port: 8084
