spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product-microservice
          uri: lb://PRODUCT-MICROSERVICE  #instead of localhost use [service discovery]
          predicates:
            - Path=/api/products/**
        - id: user-microservice
          uri: lb://USER-MICROSERVICE   #instead of localhost use [service discovery] to locate microservice (u can have multiple instance on 8081,8082,..)
          predicates:
            - Path=/api/users/**
        - id: order-microservice
          uri: lb://ORDER-MICROSERVICE  #instead of localhost use [service discovery]
          predicates:
            - Path=/api/orders/**, /api/cart/**,

#For Zipkin tracing
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

server:
  port: 8080