
#This is shared configuration file by all microservices
#prop mentioned here will be applicable for all
app:
  centralisedMessage: "centralised CONFIG"
  message: "glas message"   #this wont be overriden bcoz priority is given to app level prop

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true     #Fix for @LoadBalanced with WebClient DNS issue