spring:
  datasource:
#    mysql 8 local
#    url: jdbc:mysql://localhost:3306/product
#    username: root
#    password: root

#    mysql docker
#    url: jdbc:mysql://localhost:3307/productdb
#    username: saurabh
#    password: root

#    Postgres neon cloud non-docker
#    url: jdbc:postgresql://ep-aged-credit-a1m6ppqh-pooler.ap-southeast-1.aws.neon.tech/product?sslmode=require&channel_binding=require
#    username: neondb_owner
#    password: <>

#    Postgres docker
    url: jdbc:postgresql://localhost:5432/productdb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8081

#logging:
#  level:
#    root: info
#
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

#  endpoint:
#    health:
#      show-details: always
#    shutdown:
#      enabled: true
#  info:
#    env:
#      enabled: true
#
#info:
#  app:
#    name: MyNewApp
#    description: App built by Saurabh
#    version: "1.0."
#    yahoo_junk: true
#
#server:
#  shutdown: graceful

app:
  message: "product message"

#logging configuration
logging:
  level:
    root: INFO
    com.ecommerce.user: TRACE
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7