spring:
  data:
    mongodb:
      #      uri: mongodb+srv://saurabhshende25:7LqtV68Jqy1BFZmT@cluster0.crkq6gc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: userdb
      uri: ${MONGO_URI}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

#  PostgresDB config
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: saurabh
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: POSTGRESQL
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect


#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8082

#logging:
#  level:
#    root: info
#
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

#  endpoint:
#    health:
#      show-details: always
#    shutdown:
#      enabled: true
#  info:
#    env:
#      enabled: true
#
#info:
#  app:
#    name: MyNewApp
#    description: App built by Saurabh
#    version: "1.0."
#    yahoo_junk: true
#
#server:
#  shutdown: graceful

app:
  message: "user message"
  centralisedMessage: "centralised CONFIG"


#logging configuration
logging:
  level:
    root: INFO
    com.ecommerce.user: TRACE
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7


#KeyCloak config
keycloak:
  admin:
    username: user
    password: user
    server-url: http://keycloak:8080
    realm: ecom-app
    client-id: admin-cli
    client-uid: 50b9df5f-36f0-430f-b1ce-858c0b9c6990  #This is clientUid of oauth2-pkce(client-id)




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true     #Fix for @LoadBalanced with WebClient DNS issue

specialDockerValue: dock123