spring:
  data:
    mongodb:
#      uri: mongodb+srv://saurabhshende25:7LqtV68Jqy1BFZmT@cluster0.crkq6gc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: userdb
      uri: ${MONGO_URI}

#  PostgresDB config
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: saurabh
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: POSTGRESQL
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect


#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8082

#logging:
#  level:
#    root: info
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always
#    shutdown:
#      enabled: true
#  info:
#    env:
#      enabled: true
#
#info:
#  app:
#    name: MyNewApp
#    description: App built by Saurabh
#    version: "1.0."
#    yahoo_junk: true
#
#server:
#  shutdown: graceful
